name: Update servers data
on:
  workflow_dispatch:
    inputs:
      provider:
        description: "VPN Provider to update"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - airvpn
          - cyberghost
          - expressvpn
          - fastestvpn
          - giganews
          - hidemyass
          - ipvanish
          - ivpn
          - mullvad
          - nordvpn
          - perfect privacy
          - privado
          - private internet access
          - privatevpn
          - protonvpn
          - purevpn
          - slickvpn
          - surfshark
          - torguard
          - vpnsecure
          - vpn unlimited
          - vyprvpn
          - windscribe
  schedule:
    - cron: "11 3 1 */1 *" # Run at 03:11 on the 1st of every month
jobs:
  update-servers-list:
    if: github.repository == 'qdm12/gluetun-servers'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
    environment: secrets
    steps:
      - uses: actions/checkout@v6

      - name: Update servers list
        run: |
          SELECTED_PROVIDER="${{ github.event.inputs.provider || 'all' }}"

          if [ "$SELECTED_PROVIDER" = "all" ]; then
            FLAGS=(-all)
          else
            FLAGS=(-providers "$SELECTED_PROVIDER")
          fi

          docker run --rm -v "$PWD/pkg/servers:/gluetun/servers" ghcr.io/qdm12/gluetun:latest \
            update "${FLAGS[@]}" \
            -proton-email "${{ secrets.PROTON_EMAIL }}" \
            -proton-password "${{ secrets.PROTON_PASSWORD }}"

      - name: Check for changes
        run: |
          if git diff --exit-code pkg/servers >/dev/null; then
            echo "Error: pkg/servers was not modified."
            exit 1
          fi

      - name: Check no other file changes
        run: |
          if ! git diff --exit-code --quiet ':!pkg/servers'; then
            echo "Error: Unexpected changes detected in files other than pkg/servers"
            git status --short
            exit 1
          fi

      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v8
        with:
          branch-suffix: timestamp
          branch: bot/update-servers-data
          base: main
          delete-branch: true
          title: "feat(providers/${{ github.event.inputs.provider || 'all' }}): servers data update"
          body: |
            This PR was automatically generated by the [Update servers data](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) workflow run.

      # - name: Merge Pull Request
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh pr merge ${{ steps.createpr.outputs.pull-request-number }} --auto -m -d
